package com.casadabencao.backend.model;

public enum Role {
    ROLE_MEMBRO,
    ROLE_LIDER,
    ROLE_VICELIDER,
    ROLE_PROFESSOR,
    ROLE_PASTOR,
    ROLE_PASTORAUXILIAR,
    ROLE_EVANGELISTA,
    ROLE_DIACONO,
    ROLE_MISSIONARIO,
    ROLE_PRESBITERO,
    ROLE_OBREIRO,
    ROLE_ADMIN,
    ROLE_VISITANTE
}
